# Generated by Django 4.2.5 on 2023-11-07 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_remove_profile_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='balance',
        ),
        migrations.AddField(
            model_name='profile',
            name='assesments',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
