from django.urls import path

from .views import *
urlpatterns = [
    path('',main_page,name='main_page_url'),
    path('projects/',ProjectsListView.as_view(),name='projects_list_url'),
    path('projects/<int:pk>/',ProjectDetailView.as_view(),name='project_detail_url'),
    path('projects/<int:pk>/delete/',ProjectDeleteView.as_view(),name='project_delete_url'),
    path('projects/create/',ProjectCreateView.as_view(),name='project_create_url'),
    path('projects/enroll/',ProjectEnrollView.as_view(),name='project_enroll_url'),
    path('projects/reports/',ReportsListView.as_view(),name='reports_list_url'),
    path('internships/reports/<int:pk>/',ReportDetailView.as_view(),name='report_detail_url'),
    path('internships/reports/<int:pk>/update/',ReportUpdateView.as_view(),name='report_update_url'),
    path('internships/',InternShipsListView.as_view(),name='internships_list_url'),
    path('internships/<int:pk>/',InternShipDetailView.as_view(),name='internship_detail_url'),
    path('internships/enroll/',InternEnrollInternShipView.as_view(),name='internship_enroll_url'),
    path('internships/<int:pk>/delete/',InternShipDeleteView.as_view(),name='internship_delete_url'),
    path('internships/<int:pk>/update/',InternShipUpdateView.as_view(),name='internship_update_url'),
    path('internships/create/',InternShipCreateView.as_view(),name='internship_create_url'),
    path('courses/',CoursesListView.as_view(),name='courses_list_url'),
    path('courses/enroll/',InternEnrollCourseView.as_view(),name='course_enroll_url'),
    path('courses/<int:pk>/',CourseDetailView.as_view(),name='course_detail_url'),
    path('courses/<int:pk>/update/',CourseUpdateView.as_view(),name='course_update_url'),
    path('courses/<int:pk>/delete/',CourseDeleteView.as_view(),name='course_delete_url'),
    path('courses/create/', CourseCreateView.as_view(), name='course_create_url'),
    path('themes/',ThemesListView.as_view(),name='themes_list_url'),
    #path('themes/enroll/', InternEnrollThemeView.as_view(), name='themes_enroll_url'),
    path('themes/<int:pk>/',ThemeDetailView.as_view(),name='theme_detail_url'),
    path('themes/<int:pk>/update', ThemeUpdateView.as_view(), name='theme_update_url'),
    path('themes/<int:pk>/delete/', ThemeDeleteView.as_view(), name='theme_delete_url'),
    path('themes/create/',ThemeCreateView.as_view(),name='theme_create_url'),
    path('tests/',TestsListView.as_view(),name='tests_list_url'),
    path('tests/<int:pk>/',TestDetailView.as_view(),name='test_detail_url'),
    path('tests/<int:pk>/base/',TestBaseTextView.as_view(),name='test_base_text_url'),
    path('tests/<int:pk>/update/', TestUpdateView.as_view(), name='test_update_url'),
    path('tests/<int:pk>/delete/', TestDeleteView.as_view(), name='test_delete_url'),
    path('tests/create/',TestCreateView.as_view(),name='test_create_url'),
    path('katas/',KatasListView.as_view(),name='katas_list_url'),
    path('katas/<int:pk>/',KataDetailView.as_view(),name='kata_detail_url'),
    path('katas/<int:pk>/update/', KataUpdateView.as_view(), name='kata_update_url'),
    path('katas/<int:pk>/delete/', KataDeleteView.as_view(), name='kata_delete_url'),
    path('katas/create/',KataCreateView.as_view(),name='kata_create_url'),
    path('katas/<int:internship_id>/<int:course_id>/<int:theme_id>/<int:pk>/train/',KataTrainView.as_view(),
         name='kata_train_url'),
    path('tests/<int:internship_id>/<int:course_id>/<int:theme_id>/<int:pk>/train/',TestTrainView.as_view(),
         name='test_train_url'),
    path('courses/unenroll/',UnEnrollChoiceInternShipView.as_view(),name='choice_internship_unenroll_url'),
    path('courses/unenroll/choise/courses/',UnEnrollCourseChoiceView.as_view(),name='course_choice_unenroll_url'),
    path('courses/unenroll/courses/',UnEnrollCourseView.as_view(),name='course_unenroll_url'),

    path('students/internships/list/',StudentInternShipDetailView.as_view(),name='student_internship_detail_url'),
    path('internshipers/project/list/',InternshiperDetailView.as_view(),name='internshiper_project_detail_url'),



]
