# Generated by Django 4.2.5 on 2023-11-01 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educa', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='assesment',
        ),
        migrations.RemoveField(
            model_name='internship',
            name='assesment',
        ),
        migrations.RemoveField(
            model_name='theme',
            name='assesment',
        ),
        migrations.AlterField(
            model_name='internship',
            name='director',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='test',
            name='base',
            field=models.JSONField(default=dict),
        ),
    ]
