# Generated by Django 4.2.5 on 2023-11-01 11:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('educa', '0003_remove_project_direction_remove_project_director_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='owner',
            field=models.ManyToManyField(related_name='course_owners', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='kata',
            name='owner',
            field=models.ManyToManyField(related_name='kata_owners', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='test',
            name='owner',
            field=models.ManyToManyField(related_name='test_owners', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='theme',
            name='owner',
            field=models.ManyToManyField(related_name='theme_owners', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='internship',
            name='direction',
        ),
        migrations.RemoveField(
            model_name='internship',
            name='director',
        ),
        migrations.AlterField(
            model_name='project',
            name='director',
            field=models.ManyToManyField(related_name='project_directors', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='internship',
            name='direction',
            field=models.ManyToManyField(related_name='intern_directions', to='educa.direction'),
        ),
        migrations.AddField(
            model_name='internship',
            name='director',
            field=models.ManyToManyField(related_name='intern_directors', to=settings.AUTH_USER_MODEL),
        ),
    ]
