# Generated by Django 4.2.5 on 2023-11-03 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educa', '0004_course_owner_kata_owner_test_owner_theme_owner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='internship',
            field=models.ManyToManyField(blank=True, null=True, related_name='courses', to='educa.internship'),
        ),
        migrations.AlterField(
            model_name='project',
            name='direction',
            field=models.ManyToManyField(related_name='project_directions', to='educa.direction'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='course',
            field=models.ManyToManyField(blank=True, null=True, related_name='course_themes', to='educa.course'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='kata',
            field=models.ManyToManyField(blank=True, null=True, related_name='kata_themes', to='educa.kata'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='test',
            field=models.ManyToManyField(blank=True, null=True, related_name='test_themes', to='educa.test'),
        ),
    ]
