# Generated by Django 4.2.5 on 2023-11-03 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educa', '0005_alter_course_internship_alter_project_direction_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theme',
            name='course',
            field=models.ManyToManyField(blank=True, related_name='course_themes', to='educa.course'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='kata',
            field=models.ManyToManyField(blank=True, related_name='kata_themes', to='educa.kata'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='test',
            field=models.ManyToManyField(blank=True, related_name='test_themes', to='educa.test'),
        ),
    ]
