# Generated by Django 4.2.5 on 2023-11-03 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educa', '0006_alter_theme_course_alter_theme_kata_alter_theme_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='internship',
            field=models.ManyToManyField(blank=True, related_name='courses', to='educa.internship'),
        ),
    ]
