# Generated by Django 4.2.5 on 2023-11-03 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educa', '0007_alter_course_internship'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='base',
            field=models.JSONField(default={'': ''}),
        ),
    ]
