# Generated by Django 4.2.5 on 2023-11-03 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educa', '0008_alter_test_base'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='base',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
