# Generated by Django 4.2.5 on 2023-11-05 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educa', '0009_alter_test_base'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='base_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='kata',
            name='base',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='test',
            name='base',
            field=models.FileField(default='default.json', upload_to='tests/'),
        ),
    ]
