# Generated by Django 4.2.5 on 2023-11-05 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educa', '0010_test_base_url_alter_kata_base_alter_test_base'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='base_url',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
