# Generated by Django 4.2.5 on 2023-11-05 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('educa', '0011_alter_test_base_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='base_url',
        ),
    ]
