# Generated by Django 4.2.5 on 2023-11-06 12:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('educa', '0013_internship_interns'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='interns',
            field=models.ManyToManyField(blank=True, related_name='course_joined', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='theme',
            name='interns',
            field=models.ManyToManyField(blank=True, related_name='theme_joined', to=settings.AUTH_USER_MODEL),
        ),
    ]
