# Generated by Django 4.2.5 on 2023-11-08 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('educa', '0014_course_interns_theme_interns'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='theme',
            name='kata',
        ),
        migrations.RemoveField(
            model_name='theme',
            name='test',
        ),
        migrations.AddField(
            model_name='kata',
            name='theme',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='kata_theme', to='educa.theme'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='test',
            name='theme',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='test_theme', to='educa.theme'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='theme',
            name='course',
        ),
        migrations.AddField(
            model_name='theme',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='course_themes', to='educa.course'),
            preserve_default=False,
        ),
    ]
