# Generated by Django 4.2.5 on 2023-11-08 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educa', '0015_remove_theme_kata_remove_theme_test_kata_theme_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kata',
            name='theme',
        ),
        migrations.RemoveField(
            model_name='test',
            name='theme',
        ),
        migrations.AddField(
            model_name='theme',
            name='kata',
            field=models.ManyToManyField(blank=True, related_name='kata_themes', to='educa.kata'),
        ),
        migrations.AddField(
            model_name='theme',
            name='test',
            field=models.ManyToManyField(blank=True, related_name='test_themes', to='educa.test'),
        ),
        migrations.RemoveField(
            model_name='theme',
            name='course',
        ),
        migrations.AddField(
            model_name='theme',
            name='course',
            field=models.ManyToManyField(blank=True, related_name='course_themes', to='educa.course'),
        ),
    ]
