# Generated by Django 4.2.5 on 2023-11-14 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educa', '0021_alter_report_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='edit_field',
            field=models.TextField(blank=True, null=True),
        ),
    ]
